# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d339326bd810759a42d4bb11a189931aacd96d280240c5bdf2e5aab13c3169f7b9a96bbfaa90067ce594c0ea1cb6cf864a1895472fd0a9c988aeb993bc31484

test:
  secret_key_base: 081fe7ec6b638075ce83fd5d882747274bbdb70480eee7d98207b510b5b1beaae55d3107d7a5acd9d552518b2d29e8275c61753040665384a1ff48c2930ec9c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
